name: dev merge check

on:
  pull_request:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build:
    env:
      VITE_API_ROOT: ${{ vars.VITE_API_ROOT }}
      VITE_AMAP_KEY: ${{ vars.VITE_AMAP_KEY }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.16.0]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm ci
    - run: npm run build
