name: dev deploy

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.16.0]
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build
      run: |
        npm ci
        npm run build
    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        name: baoleme-frontend
        path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download dist
      uses: actions/download-artifact@v4
      with:
        name: baoleme-frontend
    - name: Upload dist to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.6
      with:
        username: ${{ vars.SSH_USER }}
        server: ${{ vars.SSH_HOST }}
        port: ${{ vars.SSH_PORT }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: .
        remote_path: /home/ci/frontend
